[theme]
base="light"
primaryColor="#ff4b4b" 
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#31333F"
font="sans serif"

[server]
runOnSave = true
headless = true
port = 8501
